### ISSUE TITLE
Images with transparent backgrounds reduce in quality

### ISSUE THREAD

**Issue by MichaelJamesParsons** [DavidLambauer/Magento2-WidgetImageUpload#2]
The image uploader doesn't seem to play well with images that have transparent backgrounds. A black background is added, and the overall quality drops significantly. I see this plugin is using Magento's media browser to handle the uploads.

Is it possible to retain transparent backgrounds & original quality of the image?

### Original Image
![transparent_background_test](https://user-images.githubusercontent.com/2666285/28398027-c9dd62a8-6cca-11e7-8354-6368d691c4a7.png)

### After Upload
![download](https://user-images.githubusercontent.com/2666285/28398006-ad37aad2-6cca-11e7-89ff-528df066bb88.png)

### Quality Check
I added a gray background to the same image to see if the quality drops. As you can see, images with solid backgrounds have no reduction in quality.
![full_background_test](https://user-images.githubusercontent.com/2666285/28397994-99e6d26e-6cca-11e7-9f4d-b452c18c6364.png)

**Comment by DavidLambauer** [comment]
Hi @MichaelJamesParsons, thank you for opening that issue. I haven't looked into it, but that kind of issue seems like a Magento 2 Core one. What this module does, is to open the Core functionality of the Media Library. 

Did you encounter the same behavior on the Image Upload somewhere else, for example, the CMS Page?

If you do so, this issue should be moved to M2. If the Core Image Uploader from (e.g.) the CMS Pages work well, I would appreciate some more information about your Version of M2. You may also pass me a set of images, so I can have the same environment.

Thank you,

Greetings David

**Comment by MichaelJamesParsons** [comment]
@DavidLambauer 

The product image uploader will replace transparent backgrounds with white and no reduction in quality. I haven't tested this with a CMS page.

I'm out of town for the next couple days, but I'll do further testing and submit and update as soon as I get back.

**Comment by MichaelJamesParsons** [comment]
@DavidLambauer 

You're correct, the loss of transparency also occurs in the CMS editor. I've moved this issue to the official repo.

[Submitted Issue](https://github.com/magento/magento2/issues/10343)
